library(dplyr)
library(ggplot2)
library(ggrepel)
# Read fai file generated by samtools
fai_file <- read.table(choose.files(), header = FALSE, sep = "\t", stringsAsFactors = FALSE)
colnames(fai_file) <- c("Chromosome", "Length", "Offset", "Bases_per_line","Bytes_per_line")
# Read the bed file generated by RepeatMasker
bed_file <- read.table(choose.files(), header = FALSE, sep = "\t", stringsAsFactors = FALSE)
colnames(bed_file) <- c("Chromosome","Start","End","Repeat","Score","Direction")
# Merge the fai and bed file
data_repeat <- merge(bed_file, fai_file[, c("Chromosome", "Length")], by = "Chromosome", all.x = TRUE)

chromosome_length <- data_repeat %>%
  group_by(Chromosome) %>%
  summarise(Length = max(Length)) %>%
  mutate(Start = 0, End = Length)

# Plot the repeat data according to chromosomes
ggplot(data_repeat, aes(xmin = Start, xmax = End, ymin = 0, ymax = 1, fill = Repeat)) +
  geom_rect(alpha = 0.6, color = "black") +  # 绘制重复区间的矩形
  geom_rect(data = chromosome_length, aes(xmin = 0, xmax = End, ymin = -0.1, ymax = 0), fill = "lightblue", color = NA) +  # 添加染色体长度条形图
  facet_wrap(~ Chromosome, scales = "free_y", ncol = 1) +  # 按染色体分面，每行一个
  scale_x_continuous(limits = c(0, max(data_repeat$Length))) +  # X 轴范围取决于 Length
  labs(
    title = "Repeat Regions per Chromosome",
    x = "Genomic Position (bp)",
    y = NULL
  ) +
  theme_minimal() +
  theme(
    strip.text = element_text(size = 10, face = "bold"),  # 分面标题样式
    axis.text.y = element_blank(),  # 隐藏 Y 轴标签
    axis.ticks.y = element_blank(),  # 隐藏 Y 轴刻度
    legend.position = "none",  # 取消图例
    panel.spacing = unit(0.5, "lines")  # 增加面板间距，避免重叠
  )



# Optional: Take one/multiple chromosome out
selected_chromosome <- c("dmel_4_Contig119_24176_68785")
data_repeat <- subset(data_repeat, Chromosome %in% selected_chromosome)
chromosome_length <- subset(chromosome_length, Chromosome %in% selected_chromosome)
ggplot(data_repeat, aes(xmin = Start, xmax = End, ymin = 0, ymax = 1, fill = Repeat)) +
  geom_rect(alpha = 0.6, color = "black") +  # 绘制重复区间的矩形
  geom_rect(data = chromosome_length, aes(xmin = 0, xmax = End, ymin = -0.1, ymax = 0), fill = "lightblue", color = NA) +  # 添加染色体长度条形图
  facet_wrap(~ Chromosome, scales = "free_y", ncol = 1) +  # 按染色体分面，每行一个
  scale_x_continuous(limits = c(0, max(data_repeat$Length))) +  # X 轴范围取决于 Length
  labs(
    title = "Repeat Regions per Chromosome",
    x = "Genomic Position (bp)",
    y = NULL
  ) +
  theme_minimal() +
  theme(
    strip.text = element_text(size = 10, face = "bold"),  # 分面标题样式
    axis.text.y = element_blank(),  # 隐藏 Y 轴标签
    axis.ticks.y = element_blank(),  # 隐藏 Y 轴刻度
    legend.position = "right",  # 图例放在右侧
    panel.spacing = unit(0.5, "lines")  # 增加面板间距，避免重叠
  )

ggplot(data_repeat, aes(xmin = Start, xmax = End, ymin = 0, ymax = 1, fill = Repeat)) +
  geom_rect(alpha = 0.6, color = "black") +  # 绘制重复区间的矩形
  geom_rect(data = chromosome_length, aes(xmin = 0, xmax = End, ymin = -0.1, ymax = 0), fill = "lightblue", color = NA) +  # 添加染色体长度条形图
  facet_wrap(~ Chromosome, scales = "free_y", ncol = 1) +  # 按染色体分面，每行一个
  scale_x_continuous(limits = c(0, max(data_repeat$Length))) +  # X 轴范围取决于 Length
  labs(
    title = "Repeat Regions per Chromosome",
    x = "Genomic Position (bp)",
    y = NULL
  ) +
  # 添加标签
  geom_text(aes(x = (Start + End) / 2, y = 1.05, label = paste(Start, "-", End)), size = 3, color = "black", check_overlap = TRUE) +  # 显示起始和终止位置
  theme_minimal() +
  theme(
    strip.text = element_text(size = 10, face = "bold"),  # 分面标题样式
    axis.text.y = element_blank(),  # 隐藏 Y 轴标签
    axis.ticks.y = element_blank(),  # 隐藏 Y 轴刻度
    legend.position = "right",  # 图例放在右侧
    panel.spacing = unit(0.5, "lines")  # 增加面板间距，避免重叠
  )